# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbb8c2041de0521e191422ac60fe38eb5f1fb13e0c3eb0bd1a60439833bfd2c23338b23bd5f0ddcd8320f0c7cbf2da07e4d764778480a2a6de2e266cb6c43393

test:
  secret_key_base: dbb615f31ea34da268fa1453a8867c2aeb1f4f03da0e594de4715d54d5efaf0a892ddc297776eb6d6cf8e243be0731cae30bc0a3560a71a966a2132856cb7569

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
